### ISSUE TITLE
Namespace path error causes Laravel package discovery error when added to Laravel project

### ISSUE THREAD

**Issue by sesopenko** [trycourier/courier-php-deprecated#2]
## Expected Behavior

Can add to Laravel project without error

## Actual Behavior

Service provider & facade resolution has errors.

```
php laravel/artisan view:clear --ansi

In ProviderRepository.php line 208:

  Class 'Digs\Courier\Laravel\CourierServiceProvider' not found
```

The namespaces are incorrect in the `extra` block of `composer.json`, which makes it impossible for laravel to load the provider & facade during package discover.

* `"Digs\\Courier\\Laravel\\Providers\\CourierServiceProvider"`
  * Providers namespace path is missing
* `"Digs\\Courier\\Laravel\\Facades\\CourierFacade"`
  * Facades namespace path is missing

## Steps to Reproduce the Problem

  1. scaffold blank laravel project
  1. `composer require digs/courier-sdk-php`
  1. run an artisan command which'll trigger service resolution: `php laravel/artisan view:clear --ansi`

## Specifications

  - Version: courier lib v0.10, laravel v7
  - Platform: PHP 7.2
  - Subsystem: n/a

**Comment by sesopenko** [comment]
Open PR for this issue: https://github.com/trycourier/courier-php/pull/1

**Comment by DannyDouglass** [comment]
👋  @sesopenko - thanks for submitting the pr! You might have noticed I merge it in a few days ago. 

I wanted to update you that I've published a new package that includes your changes (note the new namespace `Courier` though): https://packagist.org/packages/trycourier/courier

The previous php sdk owner was a open source effort driven by a customer, however that company is no longer operating unfortunately. 

Moving forward, the Courier team will manage this sdk: https://github.com/trycourier/courier-php

Let me know if you have any issues making the switch.
